services:
  backend:
    build: ../../backend
    container_name: backend_hack_2025
    ports:
      - "8000:8000"
    volumes:
      - ../../backend:/app
    environment:
      - CUDA_VISIBLE_DEVICES=0
    restart: unless-stopped
    networks:
      - hack_2025

  frontend:
    build:
      context: ../../frontend_v2.0
      target: dev
    image: frontend_dev_v2.0:dev
    container_name: frontend_hack_2025
    restart: unless-stopped
    volumes:
      - ../../frontend_v2.0:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - hack_2025
  
  proxy:
    image: nginx:latest
    container_name: proxy_hack_2025
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../backend/media:/backend/media/
      - ../../backend/output:/backend/output/
    restart: unless-stopped
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - frontend
    networks:
      - hack_2025

networks:
  hack_2025:
    internal: false